/// @file wrapper.cpp
/// @brief Minimal Rust FFI bindings for middleware_rs

#include <middleware_rs/middleware.hpp>

// CXX-generated header (generated by corrosion_add_cxxbridge)
#include "jr_rust_middleware_cxxbridge/ffi/bridge.h"

namespace jr::mw {

namespace detail {

struct PublisherImpl {
  ::rust::Box<::jr::mw::RustPublisher> inner;

  explicit PublisherImpl(::rust::Box<::jr::mw::RustPublisher> pub)
      : inner(std::move(pub)) {
  }
};

struct SubscriberImpl {
  ::rust::Box<::jr::mw::RustSubscriber> inner;

  explicit SubscriberImpl(::rust::Box<::jr::mw::RustSubscriber> sub)
      : inner(std::move(sub)) {
  }
};

void delete_publisher_impl(const PublisherImpl* p) {
  delete p;
}

void delete_subscriber_impl(const SubscriberImpl* p) {
  delete p;
}

PublisherPtr create_publisher_impl(
  const std::string& topic,
  Qos qos,
  const std::size_t capacity
) {
  const auto ffi_qos = static_cast<::jr::mw::QosKind>(qos);
  auto box = ::jr::mw::create_publisher(topic, ffi_qos, capacity);
  return PublisherPtr(new PublisherImpl(std::move(box)));
}

bool publish_impl(
  const PublisherImpl* impl,
  const void* data,
  const std::size_t len
) {
  if (!impl) {
    return false;
  }

  const ::rust::Slice slice(static_cast<const std::uint8_t*>(data), len);
  const auto result = ::jr::mw::publish_bytes(*impl->inner, slice);
  return result.success;
}

bool publisher_valid_impl(const PublisherImpl* impl) {
  if (!impl) {
    return false;
  }
  return ::jr::mw::publisher_is_valid(*impl->inner);
}

SubscriberPtr create_subscriber_impl(
  const std::string& topic,
  Qos qos,
  const std::size_t capacity
) {
  const auto ffi_qos = static_cast<::jr::mw::QosKind>(qos);
  auto box = ::jr::mw::create_subscriber(topic, ffi_qos, capacity);
  return SubscriberPtr(new SubscriberImpl(std::move(box)));
}

bool subscriber_valid_impl(const SubscriberImpl* impl) {
  if (!impl) {
    return false;
  }
  return ::jr::mw::subscriber_is_valid(*impl->inner);
}

int subscriber_fd_impl(const SubscriberImpl* impl) {
  if (!impl) {
    return -1;
  }
  return ::jr::mw::subscriber_get_fd(*impl->inner);
}

RecvResult subscriber_recv_impl(SubscriberImpl* impl) {
  RecvResult result{false, {}, false};

  if (!impl) {
    result.closed = true;
    return result;
  }

  auto ffi_result = ::jr::mw::subscriber_try_recv(*impl->inner);
  result.has_message = ffi_result.has_message;
  result.closed = ffi_result.closed;

  if (ffi_result.has_message) {
    result.data.reserve(ffi_result.data.size());
    result.data.assign(ffi_result.data.begin(), ffi_result.data.end());
  }

  return result;
}

} // namespace detail

namespace rs {

bool init() {
  return ::jr::mw::middleware_init();
}

bool topic_exists(const std::string& topic) {
  const ::rust::Str rust_topic(topic.data(), topic.size());
  return ::jr::mw::topic_exists(rust_topic);
}

std::size_t subscriber_count(const std::string& topic) {
  const ::rust::Str rust_topic(topic.data(), topic.size());
  return ::jr::mw::subscriber_count(rust_topic);
}

} // namespace rs

} // namespace jr::mw
