/// @file wrapper.cpp
/// @brief C++ wrapper implementation bridging to CXX-generated FFI
///
/// This file includes the CXX-generated headers and implements the detail
/// functions that the header-only templates call into.

#include <middleware_rs/middleware.hpp>

// CXX-generated header (generated by cargo build)
#include "middleware_rs/src/ffi/bridge.rs.h"

#include <cstdint>

namespace jr::mw {

// ============================================================================
// Implementation Types (pimpl)
// ============================================================================

namespace detail {

/// Publisher implementation wrapping CXX Box
struct PublisherImpl {
    ::rust::Box<::jr::mw::RustPublisher> inner;
    
    explicit PublisherImpl(::rust::Box<::jr::mw::RustPublisher> pub)
        : inner(std::move(pub))
    {}
};

/// Subscriber implementation wrapping CXX Box
struct SubscriberImpl {
    ::rust::Box<::jr::mw::RustSubscriber> inner;
    
    explicit SubscriberImpl(::rust::Box<::jr::mw::RustSubscriber> sub)
        : inner(std::move(sub))
    {}
};

// Custom deleters for pimpl (used by unique_ptr)
void delete_publisher_impl(PublisherImpl* p) {
    delete p;
}

void delete_subscriber_impl(SubscriberImpl* p) {
    delete p;
}

} // namespace detail

// ============================================================================
// Middleware Lifecycle
// ============================================================================

bool init() {
    return ::jr::mw::middleware_init();
}

bool topic_exists(const std::string& topic) {
    return ::jr::mw::topic_exists(topic);
}

std::size_t subscriber_count(const std::string& topic) {
    return ::jr::mw::subscriber_count(topic);
}

// ============================================================================
// Publisher Detail Functions
// ============================================================================

namespace detail {

PublisherPtr create_publisher_impl(
    const std::string& topic,
    Qos qos,
    std::size_t capacity
) {
    auto ffi_qos = static_cast<::jr::mw::QosKind>(qos);
    auto box = ::jr::mw::create_publisher(topic, ffi_qos, capacity);
    return PublisherPtr(new PublisherImpl(std::move(box)));
}

bool publish_impl(const PublisherImpl* impl, const void* data, std::size_t len) {
    if (!impl) return false;
    
    ::rust::Slice<const std::uint8_t> slice(
        static_cast<const std::uint8_t*>(data),
        len
    );
    
    auto result = ::jr::mw::publish_bytes(*impl->inner, slice);
    return result.success;
}

bool publisher_valid_impl(const PublisherImpl* impl) {
    if (!impl) return false;
    return ::jr::mw::publisher_is_valid(*impl->inner);
}

// ============================================================================
// Subscriber Detail Functions
// ============================================================================

SubscriberPtr create_subscriber_impl(
    const std::string& topic,
    Qos qos,
    std::size_t capacity
) {
    auto ffi_qos = static_cast<::jr::mw::QosKind>(qos);
    auto box = ::jr::mw::create_subscriber(topic, ffi_qos, capacity);
    return SubscriberPtr(new SubscriberImpl(std::move(box)));
}

bool subscriber_valid_impl(const SubscriberImpl* impl) {
    if (!impl) return false;
    return ::jr::mw::subscriber_is_valid(*impl->inner);
}

int subscriber_fd_impl(const SubscriberImpl* impl) {
    if (!impl) return -1;
    return ::jr::mw::subscriber_get_fd(*impl->inner);
}

RecvResult subscriber_recv_impl(SubscriberImpl* impl) {
    RecvResult result{false, {}, false};
    
    if (!impl) {
        result.closed = true;
        return result;
    }
    
    auto ffi_result = ::jr::mw::subscriber_try_recv(*impl->inner);
    
    result.has_message = ffi_result.has_message;
    result.closed = ffi_result.closed;
    
    if (ffi_result.has_message) {
        // Copy from rust::Vec to std::vector (unavoidable at FFI boundary)
        // Pre-allocate to avoid reallocations
        result.data.reserve(ffi_result.data.size());
        result.data.assign(ffi_result.data.begin(), ffi_result.data.end());
    }
    
    return result;  // NRVO or move semantics apply
}

} // namespace detail

} // namespace jr::mw
